ARG FROM=ubuntu:latest

FROM $FROM

USER root

ENV DEBIAN_FRONTEND=noninteractive

ADD . /tmp/setup

WORKDIR /var/local

RUN <<EOF
#!/usr/bin/env bash

chmod +x "/tmp/setup/setup.sh"

"/tmp/setup/setup.sh"

rm -rf "/tmp/setup"

EOF

ENTRYPOINT [ "/usr/bin/env", "bash", "-l" ]
