ARG FROM=ubuntu:latest

FROM $FROM

USER root

ENV DEBIAN_FRONTEND=noninteractive

ADD . /tmp/setup

WORKDIR /var/local

ENTRYPOINT [ "/usr/bin/env", "bash", "-l" ]

RUN <<EOF
#!/usr/bin/env bash

# update
apt-get update
apt-get install -y \
    curl

# setup host
script=$(curl -fsSL "https://raw.githubusercontent.com/softvisio/scripts/main/setup-host.sh")
source <(echo "$script")

# install dependencies
apt-get install -y \
    apt-utils \
    git \
    gcc \
    g++ \
    make \
    cmake \
    libssl-dev \
    gpg

EOF
